package com.example.sharangirdhani.homework06;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.Required;

/**
 * Created by sharangirdhani on 11/4/17.
 */

public class User extends RealmObject {

    @PrimaryKey
    private String          username;
    @Required
    private String          password;
    @Override
    public String toString() {
        return "User"+ "Name "+username+"Password "+password;
    }

    // Standard getters & setters generated by your IDE…
    public String getName() { return username; }
    public void   setName(String username) { this.username = username; }
    public String    getPassword() { return password; }
    public void   setPassword(String password) { this.password = password; }

}
